# Generated by Django 3.0.7 on 2020-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200612_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
    ]
