# Generated by Django 3.0.7 on 2020-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_remove_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=0, upload_to='youtube/videos/'),
            preserve_default=False,
        ),
    ]
