# Generated by Django 3.0.7 on 2020-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='django_youtube/media/'),
        ),
    ]
