# Generated by Django 3.0.7 on 2020-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20200618_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
